package myApp.list;

public class LocationListItem {
	private int locationId; // automatically generated by database
	private String name; // name of the location
	private double latitude; // latitude (-90 to +90)
	private double longitude; // longitude (-180 to +180)
	private float radius; // radius of the location (in meters)

	private String address; // address of the location

	// Constructor
	public LocationListItem(int id, String name, double latitude,
			double longitude, float radius, String address) {
		locationId = id;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.radius = radius;
		this.address = address;
	}
	
	public LocationListItem(String name, double latitude,
			double longitude, float radius) {
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.radius = radius;
		address = "No address was found for this location";
	}

	// GETTERS
	public int getLocationId() {
		return locationId;
	}

	public String getName() {
		return name;
	}

	public double getLatitude() {
		return latitude;
	}

	public double getLongitude() {
		return longitude;
	}

	public float getRadius() {
		return radius;
	}

	public String getAddress() {
		return address;
	}

	// SETTERS
	public void setName(String name) {
		this.name = name;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public void setRadius(float radius) {
		this.radius = radius;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
